baseurl = "https://dave.blue" # Hostname (and path) to the root.
title = "David Rehmat" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en"

paginate = 20
pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "drehmat" # Enable or disable Disqus.

[params] # theme parameters
    author = "David Rehmat" # Author's name.
    info = "WEB ENGINEER" # Author's job title or info.
    description = "David Rehmat's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "(╥﹏╥)" # Add fixedbar content
    fixedbarContentAfter = "(ヘ･_･)ヘ┳━┳" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail
	
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/daretodave"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/drehmat/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"